# Generated by Django 3.2.3 on 2021-05-15 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Наименование')),
                ('protein', models.FloatField(verbose_name='Белки')),
                ('carb', models.FloatField(verbose_name='Углеводы')),
                ('fat', models.FloatField(verbose_name='Жиры')),
                ('fibre', models.FloatField(verbose_name='Клетчатка')),
                ('vitaminC', models.FloatField(verbose_name='Витамин C')),
                ('vitaminD', models.FloatField(verbose_name='Витамин D')),
                ('vitaminA', models.FloatField(verbose_name='Витамин А')),
                ('vitaminE', models.FloatField(verbose_name='Витамин Е')),
                ('vitaminB2', models.FloatField(verbose_name='Витамин B2')),
                ('vitaminB5', models.FloatField(verbose_name='Витамин B5')),
                ('vitaminB6', models.FloatField(verbose_name='Витамин B6')),
                ('vitaminB9', models.FloatField(verbose_name='Витамин B9')),
                ('vitaminB12', models.FloatField(verbose_name='Витамин B12')),
                ('Fe', models.FloatField(verbose_name='Железо')),
                ('Ca', models.FloatField(verbose_name='Кальций')),
                ('K', models.FloatField(verbose_name='Калий')),
                ('Mg', models.FloatField(verbose_name='Магний')),
                ('Zn', models.FloatField(verbose_name='Цинк')),
                ('cost', models.DecimalField(decimal_places=2, max_digits=9, verbose_name='Цена')),
            ],
        ),
    ]
