# Generated by Django 3.2.3 on 2021-05-15 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='kcal',
            field=models.FloatField(default=0, verbose_name='Калории'),
        ),
        migrations.AlterField(
            model_name='product',
            name='Ca',
            field=models.FloatField(default=0, verbose_name='Кальций'),
        ),
        migrations.AlterField(
            model_name='product',
            name='Fe',
            field=models.FloatField(default=0, verbose_name='Железо'),
        ),
        migrations.AlterField(
            model_name='product',
            name='K',
            field=models.FloatField(default=0, verbose_name='Калий'),
        ),
        migrations.AlterField(
            model_name='product',
            name='Mg',
            field=models.FloatField(default=0, verbose_name='Магний'),
        ),
        migrations.AlterField(
            model_name='product',
            name='Zn',
            field=models.FloatField(default=0, verbose_name='Цинк'),
        ),
        migrations.AlterField(
            model_name='product',
            name='carb',
            field=models.FloatField(default=0, verbose_name='Углеводы'),
        ),
        migrations.AlterField(
            model_name='product',
            name='cost',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=9, verbose_name='Цена'),
        ),
        migrations.AlterField(
            model_name='product',
            name='fat',
            field=models.FloatField(default=0, verbose_name='Жиры'),
        ),
        migrations.AlterField(
            model_name='product',
            name='fibre',
            field=models.FloatField(default=0, verbose_name='Клетчатка'),
        ),
        migrations.AlterField(
            model_name='product',
            name='protein',
            field=models.FloatField(default=0, verbose_name='Белки'),
        ),
        migrations.AlterField(
            model_name='product',
            name='vitaminA',
            field=models.FloatField(default=0, verbose_name='Витамин А'),
        ),
        migrations.AlterField(
            model_name='product',
            name='vitaminB12',
            field=models.FloatField(default=0, verbose_name='Витамин B12'),
        ),
        migrations.AlterField(
            model_name='product',
            name='vitaminB2',
            field=models.FloatField(default=0, verbose_name='Витамин B2'),
        ),
        migrations.AlterField(
            model_name='product',
            name='vitaminB5',
            field=models.FloatField(default=0, verbose_name='Витамин B5'),
        ),
        migrations.AlterField(
            model_name='product',
            name='vitaminB6',
            field=models.FloatField(default=0, verbose_name='Витамин B6'),
        ),
        migrations.AlterField(
            model_name='product',
            name='vitaminB9',
            field=models.FloatField(default=0, verbose_name='Витамин B9'),
        ),
        migrations.AlterField(
            model_name='product',
            name='vitaminC',
            field=models.FloatField(default=0, verbose_name='Витамин C'),
        ),
        migrations.AlterField(
            model_name='product',
            name='vitaminD',
            field=models.FloatField(default=0, verbose_name='Витамин D'),
        ),
        migrations.AlterField(
            model_name='product',
            name='vitaminE',
            field=models.FloatField(default=0, verbose_name='Витамин Е'),
        ),
    ]
