# Generated by Django 3.2.3 on 2021-05-16 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20210515_1632'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='cost',
            field=models.FloatField(default=0, verbose_name='Цена'),
        ),
    ]
